name: mat_finance
description: "MAT Finance - gestionarea clientilor si proceselor de creditare."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.9

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_svg: ^2.1.0
  shared_preferences: ^2.5.3
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.9
  uuid: ^4.5.1
  file_picker: ^10.2.0
  http: ^1.4.0
  excel: ^4.0.6
  smooth_corner: ^1.1.1
  crypto: ^3.0.3
  image: ^4.0.17
  package_info_plus: ^8.0.3
  archive: ^3.6.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  intl: 0.20.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  window_manager: ^0.5.0
  # Google Drive integration
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  google_sign_in: ^7.1.0
  url_launcher: ^6.3.1
  oauth2: ^2.0.2
  desktop_webview_auth: ^0.0.15
  path: ^1.9.0
  connectivity_plus: ^6.0.5
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/plus_outlined.svg
    - assets/close_outlined.svg
    - assets/right_outlined.svg
    - assets/caret_outlined.svg
    - assets/left_outlined.svg
    - assets/phone_outlined.svg
    - assets/chat_outlined.svg
    - assets/group_outlined.svg
    - assets/undo_outlined.svg
    - assets/retry_outlined.svg
    - assets/view_outlined.svg
    - assets/save_outlined.svg
    - assets/delete_outlined.svg
    - assets/recommend_outlined.svg
    - assets/trending_outlined.svg
    - assets/check_outlined.svg
    - assets/copy_outlined.svg
    - assets/hide_outlined.svg
    - assets/look_outlined.svg
    - assets/edit_outlined.svg
    - assets/info_outlined.svg
    - assets/clients_outlined.svg
    - assets/settings_outlined.svg
    - assets/calendar_outlined.svg
    - assets/form_outlined.svg
    - assets/dashboard_outlined.svg
    - assets/calculator_outlined.svg
    - assets/user_outlined.svg
    - assets/image_outlined.svg
    - assets/logo.svg
    - assets/moon_outlined.svg
    - assets/sun_outlined.svg
    - assets/system_outlined.svg
    - assets/color_outlined.svg
    - assets/brdIcon.svg
    - assets/bcrIcon.svg
    - assets/raiffeisenIcon.svg
    - assets/ingIcon.svg
    - assets/tbiIcon.svg
    - assets/garantiIcon.svg
    - assets/btIcon.svg
    - assets/alphaIcon.svg
    - assets/cecIcon.svg 
    - assets/logout_outlined.svg
    - assets/home_outlined.svg
    - assets/history_outlined.svg
    - assets/coffee_outlined.svg
    - assets/send_outlined.svg
    - assets/chat_outlined.svg
    - assets/minus_outlined.svg
    - assets/maximize_outlined.svg
    - assets/home_solid.svg
    - assets/calendar_solid.svg
    - assets/form_solid.svg
    - assets/clients_solid.svg
    - assets/calculator_solid.svg
    - assets/settings_solid.svg
    - assets/checkbox_outlined.svg
    - assets/box_outlined.svg
    - assets/trade_outlined.svg

# Launcher icons configuration (do not run generation here; user executes the command)
flutter_launcher_icons:
  image_path: "assets/logo_mat.png"
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/logo_mat.png"
    background_color: "#00000000"
  windows:
    generate: true
    image_path: "assets/logo_mat.ico"
  macos:
    generate: true
    image_path: "assets/logo_mat.png"
  linux:
    generate: true
    image_path: "assets/logo_mat.png"