// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmkOMU2YvyJyCa72Lm1D3i62xS9uVISvY',
    appId: '1:324961203074:web:aebb2c8a1fbdd12307559b',
    messagingSenderId: '324961203074',
    projectId: 'broker-app-f1n4nc3',
    authDomain: 'broker-app-f1n4nc3.firebaseapp.com',
    storageBucket: 'broker-app-f1n4nc3.firebasestorage.app',
    measurementId: 'G-RQYQ68D69W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr0N-3rXc_KNz5nxM4JG9cCbNLsm8rFu8',
    appId: '1:324961203074:android:a49e09c8f2d20d6807559b',
    messagingSenderId: '324961203074',
    projectId: 'broker-app-f1n4nc3',
    storageBucket: 'broker-app-f1n4nc3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMxDPWmCbHRXL9qhuNxDFzY7f8IY1oHtA',
    appId: '1:324961203074:ios:7f8c65d4099a996207559b',
    messagingSenderId: '324961203074',
    projectId: 'broker-app-f1n4nc3',
    storageBucket: 'broker-app-f1n4nc3.firebasestorage.app',
    iosBundleId: 'com.example.brokerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMxDPWmCbHRXL9qhuNxDFzY7f8IY1oHtA',
    appId: '1:324961203074:ios:7f8c65d4099a996207559b',
    messagingSenderId: '324961203074',
    projectId: 'broker-app-f1n4nc3',
    storageBucket: 'broker-app-f1n4nc3.firebasestorage.app',
    iosBundleId: 'com.example.brokerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmkOMU2YvyJyCa72Lm1D3i62xS9uVISvY',
    appId: '1:324961203074:web:d67064b2b9ae146707559b',
    messagingSenderId: '324961203074',
    projectId: 'broker-app-f1n4nc3',
    authDomain: 'broker-app-f1n4nc3.firebaseapp.com',
    storageBucket: 'broker-app-f1n4nc3.firebasestorage.app',
    measurementId: 'G-NKE39RD50B',
  );
}
